name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test File I/O
      id: test-file-i-o
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: sudo -H pip3 install pytest
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-FILE-I-O_RESULTS: "${{steps.test-file-i-o.outputs.result}}"
      with:
        runners: test-file-i-o
